services:
  db:
    restart: always
    image: postgres:latest
    container_name: game-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    restart: always
    build:
      context: ./GodotMultiplayerGameBackend
      dockerfile: Dockerfile
    container_name: game-backend
    volumes:
      - ./GodotMultiplayerGameBackend:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:5432/${POSTGRES_DB}
      PORT: ${BACKEND_PORT}
      GIN_MODE: ${GIN_MODE}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${BACKEND_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  auth:
    restart: always
    platform: linux/amd64
    build:
      context: ./GodotMultiplayerGameAuth
      dockerfile: ../Dockerfile.godot
    container_name: game-auth
    depends_on:
      backend:
        condition: service_healthy
    environment:
      BACKEND_URL: http://game-backend:${BACKEND_PORT}
      AUTH_SERVER_PORT: ${AUTH_SERVER_PORT}
      AUTH_GAME_PORT: ${AUTH_GAME_PORT}
    ports:
      - "${AUTH_SERVER_PORT}:${AUTH_SERVER_PORT}"
      - "${AUTH_GAME_PORT}:${AUTH_GAME_PORT}"

  gateway:
    restart: always
    build:
      context: ./GodotMultiplayerGameGateway
      dockerfile: ../Dockerfile.godot
    container_name: game-gateway
    depends_on:
      - auth
    environment:
      AUTH_IP: ${AUTH_IP}
      AUTH_PORT: ${AUTH_PORT}
      GATEWAY_PORT: ${GATEWAY_PORT}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}/udp"

  server:
    restart: always
    build:
      context: ./GodotMultiplayerGameServer
      dockerfile: ../Dockerfile.godot
    container_name: game-server
    depends_on:
      - auth
    environment:
      AUTH_IP: ${AUTH_IP}
      AUTH_GAME_PORT: ${AUTH_GAME_PORT}
      GAME_SERVER_PORT: ${GAME_SERVER_PORT}
    ports:
      - "${GAME_SERVER_PORT}:${GAME_SERVER_PORT}/udp"

volumes:
  postgres_data:
