services:
  db:
    restart: always
    image: postgres:latest
    container_name: game-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    restart: always
    build:
      context: ./GodotMultiplayerGameBackend
      dockerfile: Dockerfile
    container_name: game-backend
    volumes:
      - ./GodotMultiplayerGameBackend:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:5432/${POSTGRES_DB}
      PORT: ${BACKEND_PORT}
      GIN_MODE: ${GIN_MODE}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${BACKEND_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
